### ISSUE TITLE
Comparison to ember-burger-menu

### ISSUE THREAD

**Issue by deepflame** [rajasegar/ember-slide-push-menu#1]
Hi @rajasegar ,

thanks for sharing this addon with the Ember-community.
Currently we are using https://github.com/offirgolan/ember-burger-menu .

How does this addon compare to this one here and why would I consider moving over?
Would appreciate your insights here.

Thanks
Andreas

**Comment by rajasegar** [comment]
@deepflame Thanks for the appreciation, i would say that, it may not be a good thing to compare this with burger menu. Since burger menu is far more advanced, battle tested and feature rich than ours. I would say if you just want a simple offcanvas-menu you can use this addon or if you want more control and customization you can go for burger-menu.
I really appreciate that the author of burger-menu has done a tremendous job.
Ours is just starting up in the addon space... Will be adding more features in the near future..

**Comment by deepflame** [comment]
@rajasegar Thanks for your honest reply. Appreciate it. What I could see from the demos is that it is possible to create an offcanvas-menu from the top and bottom with your addon. Not sure if this is possible with burger-menu.

Anyways. Good luck with your addon!
